"""renamed back to address

Revision ID: df96bbdc465e
Revises: 2173e3876731
Create Date: 2025-01-16 16:56:58.838685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df96bbdc465e'
down_revision = '2173e3876731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=False))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
